// <auto-generated />
using System;
using Conference.CheckIn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conference.CheckIn.Data.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    [Migration("20181108113650_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Conference.CheckIn.Data.Model.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthdate");

                    b.Property<DateTime?>("CheckInTime");

                    b.Property<bool>("CheckedIn");

                    b.Property<string>("City")
                        .HasMaxLength(255);

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("EventId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Gender")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Phone")
                        .HasMaxLength(255);

                    b.Property<string>("Room")
                        .HasMaxLength(255);

                    b.Property<string>("Street")
                        .HasMaxLength(255);

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Zip")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("Conference.CheckIn.Data.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Conference.CheckIn.Data.Model.Attendee", b =>
                {
                    b.HasOne("Conference.CheckIn.Data.Model.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
